### ISSUE TITLE
睡眠无法唤醒可以用以下解决

### ISSUE THREAD

**Issue by freechinanet** [17374363415/dell-vostro-3681-efi#7]
https://www.cnblogs.com/pdblogs/p/15906453.html   我是用这个链接的方法解决的。只用第二步就可以解决。2、解决睡眠后无法唤醒、唤醒后显示器无输出问题：在启动命令行中添加：igfxonln=1

**Comment by 17374363415** [comment]
感谢支持，此方法测试后无效，在硬盘睡眠后无法唤醒，直接重启，但还是要感谢你提供方法
